@echo off
echo Checking project env config...
if not exist venv (
    echo Building local Python environment...
    python -m venv venv
)
echo Activating runtime environment dependencies...
call venv\Scripts\activate
pip install -r requirements.txt --quiet
echo Launching MCP bridge...
python bridge.py
pause